# This is a generated file. Not intended for manual editing.
services:
  approval.service:
    build:
      context: "D:\\PersonalProjects\\DDMS"
      dockerfile: "Approval.Service/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57408"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "approval.service:dev"
    ports:
    - "127.0.0.1:57008:57000"
    - "127.0.0.1:57208:57200"
    - "127.0.0.1:57408:57408"
    volumes:
    - "D:\\PersonalProjects\\DDMS\\Approval.Service:/app:rw"
    - "D:\\PersonalProjects\\DDMS:/src:rw"
    - "C:\\Users\\Karim Tarek\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.1.3\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.6\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_14_14_09_09:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  auditlog.service:
    build:
      context: "D:\\PersonalProjects\\DDMS"
      dockerfile: "AuditLog.Service/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57409"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "auditlog.service:dev"
    ports:
    - "127.0.0.1:57009:57000"
    - "127.0.0.1:57209:57200"
    - "127.0.0.1:57409:57409"
    volumes:
    - "D:\\PersonalProjects\\DDMS\\AuditLog.Service:/app:rw"
    - "D:\\PersonalProjects\\DDMS:/src:rw"
    - "C:\\Users\\Karim Tarek\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.1.3\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.6\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_14_14_09_09:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  ddms.gateway:
    build:
      context: "D:\\PersonalProjects\\DDMS"
      dockerfile: "DDMS.Gateway/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57410"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ddms.gateway:dev"
    ports:
    - "127.0.0.1:57010:57000"
    - "127.0.0.1:57210:57200"
    - "127.0.0.1:57410:57410"
    volumes:
    - "D:\\PersonalProjects\\DDMS\\DDMS.Gateway:/app:rw"
    - "D:\\PersonalProjects\\DDMS:/src:rw"
    - "C:\\Users\\Karim Tarek\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.1.3\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.6\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_14_14_09_09:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  documents.service:
    build:
      context: "D:\\PersonalProjects\\DDMS"
      dockerfile: "Documents.Service/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57411"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "documents.service:dev"
    ports:
    - "127.0.0.1:57011:57000"
    - "127.0.0.1:57211:57200"
    - "127.0.0.1:57411:57411"
    volumes:
    - "D:\\PersonalProjects\\DDMS\\Documents.Service:/app:rw"
    - "D:\\PersonalProjects\\DDMS:/src:rw"
    - "C:\\Users\\Karim Tarek\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.1.3\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.6\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_14_14_09_09:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  fileprocessor.service:
    build:
      context: "D:\\PersonalProjects\\DDMS"
      dockerfile: "FileProcessor.Service/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57412"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "fileprocessor.service:dev"
    ports:
    - "127.0.0.1:57012:57000"
    - "127.0.0.1:57212:57200"
    - "127.0.0.1:57412:57412"
    volumes:
    - "D:\\PersonalProjects\\DDMS\\FileProcessor.Service:/app:rw"
    - "D:\\PersonalProjects\\DDMS:/src:rw"
    - "C:\\Users\\Karim Tarek\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.1.3\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.6\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_14_14_09_09:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  notifications.service:
    build:
      context: "D:\\PersonalProjects\\DDMS"
      dockerfile: "Notifications.Service/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57413"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "notifications.service:dev"
    ports:
    - "127.0.0.1:57013:57000"
    - "127.0.0.1:57213:57200"
    - "127.0.0.1:57413:57413"
    volumes:
    - "D:\\PersonalProjects\\DDMS\\Notifications.Service:/app:rw"
    - "D:\\PersonalProjects\\DDMS:/src:rw"
    - "C:\\Users\\Karim Tarek\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.1.3\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.6\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_14_14_09_09:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  search.service:
    build:
      context: "D:\\PersonalProjects\\DDMS"
      dockerfile: "Search.Service/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57414"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "search.service:dev"
    ports:
    - "127.0.0.1:57014:57000"
    - "127.0.0.1:57214:57200"
    - "127.0.0.1:57414:57414"
    volumes:
    - "D:\\PersonalProjects\\DDMS\\Search.Service:/app:rw"
    - "D:\\PersonalProjects\\DDMS:/src:rw"
    - "C:\\Users\\Karim Tarek\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.1.3\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.6\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_14_14_09_09:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  users.service:
    build:
      context: "D:\\PersonalProjects\\DDMS"
      dockerfile: "Users.Service/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57415"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "users.service:dev"
    ports:
    - "127.0.0.1:57015:57000"
    - "127.0.0.1:57215:57200"
    - "127.0.0.1:57415:57415"
    volumes:
    - "D:\\PersonalProjects\\DDMS\\Users.Service:/app:rw"
    - "D:\\PersonalProjects\\DDMS:/src:rw"
    - "C:\\Users\\Karim Tarek\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.1.3\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.6\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Karim Tarek\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_14_14_09_09:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
